//
// Generated file, do not edit! Created by nedtool 4.6 from applications/inet_sdn/smartGrid/Command.msg.
//

#ifndef _COMMAND_M_H_
#define _COMMAND_M_H_

#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0406
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif

// dll export symbol
#ifndef INET_API
#  if defined(INET_EXPORT)
#    define INET_API  OPP_DLLEXPORT
#  elif defined(INET_IMPORT)
#    define INET_API  OPP_DLLIMPORT
#  else
#    define INET_API
#  endif
#endif



// cplusplus {{
    #include "INETDefs.h"
// }}

/**
 * Class generated from <tt>applications/inet_sdn/smartGrid/Command.msg:21</tt> by nedtool.
 * <pre>
 * // a message sent by the IEDs to the RTU reporting the current measurement
 * message Command
 * {
 *     string name; //name: all or ied_id -> to restore a faulty device
 *     int limit;
 * }
 * </pre>
 */
class INET_API Command : public ::cMessage
{
  protected:
    opp_string name_var;
    int limit_var;

  private:
    void copy(const Command& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const Command&);

  public:
    Command(const char *name=NULL, int kind=0);
    Command(const Command& other);
    virtual ~Command();
    Command& operator=(const Command& other);
    virtual Command *dup() const {return new Command(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual const char * getName() const;
    virtual void setName(const char * name);
    virtual int getLimit() const;
    virtual void setLimit(int limit);
};

inline void doPacking(cCommBuffer *b, Command& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, Command& obj) {obj.parsimUnpack(b);}


#endif // ifndef _COMMAND_M_H_

