//
// Generated file, do not edit! Created by nedtool 4.6 from applications/inet_sdn/smartGrid/SetPoints.msg.
//

#ifndef _SETPOINTS_M_H_
#define _SETPOINTS_M_H_

#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0406
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif

// dll export symbol
#ifndef INET_API
#  if defined(INET_EXPORT)
#    define INET_API  OPP_DLLEXPORT
#  elif defined(INET_IMPORT)
#    define INET_API  OPP_DLLIMPORT
#  else
#    define INET_API
#  endif
#endif



// cplusplus {{
    #include "INETDefs.h"
// }}

/**
 * Class generated from <tt>applications/inet_sdn/smartGrid/SetPoints.msg:20</tt> by nedtool.
 * <pre>
 * packet SetPoints
 * {
 *     double energyGenLimit;
 *     int powerQualityLimit;
 * }
 * </pre>
 */
class INET_API SetPoints : public ::cPacket
{
  protected:
    double energyGenLimit_var;
    int powerQualityLimit_var;

  private:
    void copy(const SetPoints& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const SetPoints&);

  public:
    SetPoints(const char *name=NULL, int kind=0);
    SetPoints(const SetPoints& other);
    virtual ~SetPoints();
    SetPoints& operator=(const SetPoints& other);
    virtual SetPoints *dup() const {return new SetPoints(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual double getEnergyGenLimit() const;
    virtual void setEnergyGenLimit(double energyGenLimit);
    virtual int getPowerQualityLimit() const;
    virtual void setPowerQualityLimit(int powerQualityLimit);
};

inline void doPacking(cCommBuffer *b, SetPoints& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, SetPoints& obj) {obj.parsimUnpack(b);}


#endif // ifndef _SETPOINTS_M_H_

