//
// Generated file, do not edit! Created by nedtool 4.6 from ofomnet/openflow/messages/OFP_Flow_Stats_Request.msg.
//

#ifndef _OFP_FLOW_STATS_REQUEST_M_H_
#define _OFP_FLOW_STATS_REQUEST_M_H_

#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0406
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif

// dll export symbol
#ifndef INET_API
#  if defined(INET_EXPORT)
#    define INET_API  OPP_DLLEXPORT
#  elif defined(INET_IMPORT)
#    define INET_API  OPP_DLLIMPORT
#  else
#    define INET_API
#  endif
#endif



// cplusplus {{
    #include "openflow.h"
    #include "Open_Flow_Message_m.h"
// }}

/**
 * Class generated from <tt>ofomnet/openflow/messages/OFP_Flow_Stats_Request.msg:13</tt> by nedtool.
 * <pre>
 * //Individual flow statistics request message
 * //The controller uses this message to query individual flow statistics.
 * packet OFP_Flow_Stats_Request extends Open_Flow_Message
 * {
 *     oxm_basic_match match;
 *     int datapath_id;
 *     uint8_t table_id;
 *     uint32_t out_port;
 * }
 * </pre>
 */
class INET_API OFP_Flow_Stats_Request : public ::Open_Flow_Message
{
  protected:
    oxm_basic_match match_var;
    int datapath_id_var;
    uint8_t table_id_var;
    uint32_t out_port_var;

  private:
    void copy(const OFP_Flow_Stats_Request& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const OFP_Flow_Stats_Request&);

  public:
    OFP_Flow_Stats_Request(const char *name=NULL, int kind=0);
    OFP_Flow_Stats_Request(const OFP_Flow_Stats_Request& other);
    virtual ~OFP_Flow_Stats_Request();
    OFP_Flow_Stats_Request& operator=(const OFP_Flow_Stats_Request& other);
    virtual OFP_Flow_Stats_Request *dup() const {return new OFP_Flow_Stats_Request(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual oxm_basic_match& getMatch();
    virtual const oxm_basic_match& getMatch() const {return const_cast<OFP_Flow_Stats_Request*>(this)->getMatch();}
    virtual void setMatch(const oxm_basic_match& match);
    virtual int getDatapath_id() const;
    virtual void setDatapath_id(int datapath_id);
    virtual uint8_t getTable_id() const;
    virtual void setTable_id(uint8_t table_id);
    virtual uint32_t getOut_port() const;
    virtual void setOut_port(uint32_t out_port);
};

inline void doPacking(cCommBuffer *b, OFP_Flow_Stats_Request& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, OFP_Flow_Stats_Request& obj) {obj.parsimUnpack(b);}


#endif // ifndef _OFP_FLOW_STATS_REQUEST_M_H_

