//
// Generated file, do not edit! Created by nedtool 4.6 from ofomnet/openflow/messages/OFP_Flow_Stats_Reply.msg.
//

#ifndef _OFP_FLOW_STATS_REPLY_M_H_
#define _OFP_FLOW_STATS_REPLY_M_H_

#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0406
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif

// dll export symbol
#ifndef INET_API
#  if defined(INET_EXPORT)
#    define INET_API  OPP_DLLEXPORT
#  elif defined(INET_IMPORT)
#    define INET_API  OPP_DLLIMPORT
#  else
#    define INET_API
#  endif
#endif



// cplusplus {{
    #include "openflow.h"
    #include "Open_Flow_Message_m.h"
    typedef ofp_flow_stats *FlowStatsPtr;
// }}

/**
 * Class generated from <tt>ofomnet/openflow/messages/OFP_Flow_Stats_Reply.msg:15</tt> by nedtool.
 * <pre>
 * packet OFP_Flow_Stats_Reply extends Open_Flow_Message
 * {
 *     int datapath_Id;
 *     FlowStatsPtr flowStatsArray[];
 * }
 * </pre>
 */
class INET_API OFP_Flow_Stats_Reply : public ::Open_Flow_Message
{
  protected:
    int datapath_Id_var;
    FlowStatsPtr *flowStatsArray_var; // array ptr
    unsigned int flowStatsArray_arraysize;

  private:
    void copy(const OFP_Flow_Stats_Reply& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const OFP_Flow_Stats_Reply&);

  public:
    OFP_Flow_Stats_Reply(const char *name=NULL, int kind=0);
    OFP_Flow_Stats_Reply(const OFP_Flow_Stats_Reply& other);
    virtual ~OFP_Flow_Stats_Reply();
    OFP_Flow_Stats_Reply& operator=(const OFP_Flow_Stats_Reply& other);
    virtual OFP_Flow_Stats_Reply *dup() const {return new OFP_Flow_Stats_Reply(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual int getDatapath_Id() const;
    virtual void setDatapath_Id(int datapath_Id);
    virtual void setFlowStatsArrayArraySize(unsigned int size);
    virtual unsigned int getFlowStatsArrayArraySize() const;
    virtual FlowStatsPtr& getFlowStatsArray(unsigned int k);
    virtual const FlowStatsPtr& getFlowStatsArray(unsigned int k) const {return const_cast<OFP_Flow_Stats_Reply*>(this)->getFlowStatsArray(k);}
    virtual void setFlowStatsArray(unsigned int k, const FlowStatsPtr& flowStatsArray);
};

inline void doPacking(cCommBuffer *b, OFP_Flow_Stats_Reply& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, OFP_Flow_Stats_Reply& obj) {obj.parsimUnpack(b);}


#endif // ifndef _OFP_FLOW_STATS_REPLY_M_H_

